// Silverback Vault V3 - Paste UPC + robust Export UPC + Export Username
// Import UPC remains username;password;cookie. Export UPC uses username:password:cookie for Winter compatibility.
(() => {
  const normUser=v=>String(v||'').trim().toLowerCase();
  const normCookie=v=>String(v||'').trim();
  const exactKey=(u,p,c)=>`${normUser(u)}\u0000${String(p||'')}\u0000${normCookie(c)}`;

  function selectedAccountIds(){return new Set([...document.querySelectorAll('[data-account-select]:checked')].map(el=>el.dataset.accountSelect).filter(Boolean))}
  function isVaultUnlocked(){try{return Boolean(masterKey&&vault&&Array.isArray(vault.accounts))}catch{return false}}

  function parseUPC(text){
    const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/);const rows=[],rejected=[],duplicateInPaste=[],seenExact=new Set(),seenUsers=new Map(),seenCookies=new Map();
    lines.forEach((raw,index)=>{const line=raw.trim();if(!line)return;const first=line.indexOf(';'),second=first>=0?line.indexOf(';',first+1):-1;if(first<=0||second<=first+1){rejected.push(index+1);return}const username=line.slice(0,first).trim(),password=line.slice(first+1,second),cookie=line.slice(second+1).trim();if(!username||!cookie){rejected.push(index+1);return}const ukey=normUser(username),ckey=normCookie(cookie),ekey=exactKey(username,password,cookie);if(seenExact.has(ekey)){duplicateInPaste.push(index+1);return}if(seenUsers.has(ukey)){const prev=seenUsers.get(ukey),old=rows[prev];if(old)seenExact.delete(exactKey(old.username,old.password,old.cookie));rows[prev]=null}if(seenCookies.has(ckey)&&seenCookies.get(ckey)!==ukey){duplicateInPaste.push(index+1);return}const now=new Date().toISOString(),row={id:crypto.randomUUID(),username,password,cookie,status:'Active',group:'Imported',notes:'Pasted UPC',createdAt:now,updatedAt:now},pos=rows.length;rows.push(row);seenUsers.set(ukey,pos);seenCookies.set(ckey,ukey);seenExact.add(ekey)});return{rows:rows.filter(Boolean),rejected,duplicateInPaste}
  }

  async function applyPastedUPC(text){if(!isVaultUnlocked())throw new Error('Unlock vault dulu');const{rows,rejected,duplicateInPaste}=parseUPC(text);if(!rows.length)throw new Error('Tidak ada baris username;password;cookie yang terbaca');const existingByUser=new Map(),existingByCookie=new Map(),existingExact=new Set();vault.accounts.forEach(a=>{const u=normUser(a.username),c=normCookie(a.cookie);if(u&&!existingByUser.has(u))existingByUser.set(u,a);if(c&&!existingByCookie.has(c))existingByCookie.set(c,a);if(u&&c)existingExact.add(exactKey(a.username,a.password,a.cookie))});let added=0,updated=0,skippedExact=0,cookieConflicts=0;for(const row of rows){const u=normUser(row.username),c=normCookie(row.cookie),e=exactKey(row.username,row.password,row.cookie);if(existingExact.has(e)){skippedExact++;continue}const old=existingByUser.get(u),cookieOwner=existingByCookie.get(c);if(cookieOwner&&cookieOwner!==old&&normUser(cookieOwner.username)!==u){cookieConflicts++;continue}if(old){const oldCookie=normCookie(old.cookie);if(oldCookie&&existingByCookie.get(oldCookie)===old)existingByCookie.delete(oldCookie);existingExact.delete(exactKey(old.username,old.password,old.cookie));old.password=row.password;old.cookie=row.cookie;old.updatedAt=new Date().toISOString();if(!old.group)old.group='Imported';existingByCookie.set(c,old);existingExact.add(e);updated++}else{vault.accounts.push(row);existingByUser.set(u,row);existingByCookie.set(c,row);existingExact.add(e);added++}}if(added||updated)await saveLocalAndMaybeRemote();render();const parts=[`${added} baru`,`${updated} diperbarui`];if(skippedExact)parts.push(`${skippedExact} duplikat dilewati`);if(duplicateInPaste.length)parts.push(`${duplicateInPaste.length} duplikat di paste dilewati`);if(cookieConflicts)parts.push(`${cookieConflicts} konflik cookie dilewati`);if(rejected.length)parts.push(`${rejected.length} baris invalid`);return parts.join(' • ')}

  function scopeAccounts(name){const scope=document.querySelector(`input[name="${name}"]:checked`)?.value||'all';if(scope==='selected'){const ids=selectedAccountIds();return vault.accounts.filter(a=>ids.has(a.id))}return[...vault.accounts]}
  async function saveTextFile(text,filename,mime='text/plain;charset=utf-8'){const safeText='\uFEFF'+String(text||'');let objectUrl=null;try{const blob=new Blob([safeText],{type:mime});objectUrl=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectUrl;a.download=filename;a.rel='noopener';a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>{try{URL.revokeObjectURL(objectUrl)}catch{}},5000);return true}catch(err){console.warn('Blob download failed, trying data URI',err);try{const a=document.createElement('a');a.href='data:'+mime+','+encodeURIComponent(safeText);a.download=filename;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();return true}catch(err2){console.error('Export download failed',err2);try{await navigator.clipboard.writeText(String(text||''));toast('Download gagal, data sudah dicopy ke clipboard.');return false}catch{}throw err2}}}

  function ensureDialogs(){
    if(!document.getElementById('pasteUpcDialog')){const d=document.createElement('dialog');d.id='pasteUpcDialog';d.innerHTML=`<div class="modal paste-upc-modal"><div class="modal-head"><div><div class="eyebrow">ACCOUNTS</div><h2>Paste UPC</h2></div><button id="closePasteUpc" type="button" class="icon-btn">×</button></div><div class="notice">Tempel satu akun per baris dengan format <b>username;password;cookie</b>. Duplicate otomatis dilewati atau diperbarui.</div><textarea id="pasteUpcText" rows="14" spellcheck="false" autocomplete="off" placeholder="username;password;cookie\nusername2;password2;cookie2"></textarea><div class="modal-actions"><span class="spacer"></span><button id="cancelPasteUpc" type="button" class="secondary">Cancel</button><button id="importPasteUpc" type="button" class="primary">Import Paste</button></div></div>`;document.body.appendChild(d);d.querySelector('#closePasteUpc').onclick=()=>d.close();d.querySelector('#cancelPasteUpc').onclick=()=>d.close();d.querySelector('#importPasteUpc').onclick=async()=>{const btn=d.querySelector('#importPasteUpc');btn.disabled=true;try{const summary=await applyPastedUPC(d.querySelector('#pasteUpcText').value);d.querySelector('#pasteUpcText').value='';d.close();toast(`Paste selesai: ${summary}`)}catch(e){console.error(e);toast('Paste gagal: '+String(e.message||e).slice(0,120))}finally{btn.disabled=false}}}
    if(!document.getElementById('exportUpcDialog')){const d=document.createElement('dialog');d.id='exportUpcDialog';d.innerHTML=`<div class="modal paste-upc-modal"><div class="modal-head"><div><div class="eyebrow">EXPORT</div><h2>Export UPC</h2></div><button id="closeExportUpc" type="button" class="icon-btn">×</button></div><div class="notice">TXT plaintext berisi <b>username:password:cookie</b> (format Winter).</div><div class="export-scope-row"><label><input type="radio" name="exportScope" value="all" checked> All accounts</label><label><input type="radio" name="exportScope" value="selected"> Selected items</label></div><div id="exportUpcCount" class="notice"></div><div class="modal-actions"><span class="spacer"></span><button id="cancelExportUpc" type="button" class="secondary">Cancel</button><button id="downloadExportUpc" type="button" class="primary">Export TXT</button></div></div>`;document.body.appendChild(d);d.querySelector('#closeExportUpc').onclick=()=>d.close();d.querySelector('#cancelExportUpc').onclick=()=>d.close();d.addEventListener('change',refreshExportCount);d.querySelector('#downloadExportUpc').onclick=downloadUPC}
    if(!document.getElementById('exportUsernameDialog')){const d=document.createElement('dialog');d.id='exportUsernameDialog';d.innerHTML=`<div class="modal paste-upc-modal"><div class="modal-head"><div><div class="eyebrow">EXPORT</div><h2>Export Username</h2></div><button id="closeExportUsername" type="button" class="icon-btn">×</button></div><div class="notice">Username saja, satu per baris. Duplicate otomatis dihapus.</div><div class="export-scope-row"><label><input type="radio" name="usernameExportScope" value="all" checked> All accounts</label><label><input type="radio" name="usernameExportScope" value="selected"> Selected items</label></div><div id="exportUsernameCount" class="notice"></div><div class="modal-actions"><button id="copyExportUsername" type="button" class="secondary">Copy Username</button><span class="spacer"></span><button id="cancelExportUsername" type="button" class="secondary">Cancel</button><button id="downloadExportUsername" type="button" class="primary">Download TXT</button></div></div>`;document.body.appendChild(d);d.querySelector('#closeExportUsername').onclick=()=>d.close();d.querySelector('#cancelExportUsername').onclick=()=>d.close();d.addEventListener('change',refreshUsernameExportCount);d.querySelector('#downloadExportUsername').onclick=downloadUsernames;d.querySelector('#copyExportUsername').onclick=copyUsernames}
    if(!document.getElementById('pasteExportStyles')){const s=document.createElement('style');s.id='pasteExportStyles';s.textContent='.paste-upc-modal{width:min(760px,calc(100vw - 24px))}.paste-upc-modal textarea{width:100%;resize:vertical;min-height:260px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.export-scope-row{display:flex;gap:18px;flex-wrap:wrap;margin:14px 0}.export-scope-row label{display:flex;align-items:center;gap:8px}';document.head.appendChild(s)}
  }
  function exportAccountsForScope(){return scopeAccounts('exportScope')}function exportUsernameAccountsForScope(){return scopeAccounts('usernameExportScope')}function usernameList(){return[...new Set(exportUsernameAccountsForScope().map(a=>String(a.username||'').trim()).filter(Boolean))]}function refreshExportCount(){const el=document.getElementById('exportUpcCount');if(el)el.textContent=`${exportAccountsForScope().length} akun akan diexport.`}function refreshUsernameExportCount(){const el=document.getElementById('exportUsernameCount');if(el)el.textContent=`${usernameList().length} username unik akan diexport.`}
  async function downloadUPC(){try{if(!isVaultUnlocked()){toast('Unlock vault dulu.');return}const list=exportAccountsForScope();if(!list.length){toast('Tidak ada akun untuk diexport.');return}const text=list.map(a=>`${String(a.username||'')}:${String(a.password||'')}:${String(a.cookie||'')}`).join('\r\n');const stamp=new Date().toISOString().slice(0,10);await saveTextFile(text,`winter-upc-${list.length}-${stamp}.txt`);toast(`${list.length} akun diexport format user:pass:cookie.`)}catch(e){console.error(e);toast('Export UPC gagal: '+String(e.message||e).slice(0,100))}}
  async function downloadUsernames(){try{if(!isVaultUnlocked()){toast('Unlock vault dulu.');return}const usernames=usernameList();if(!usernames.length){toast('Tidak ada username untuk diexport.');return}const stamp=new Date().toISOString().slice(0,10);await saveTextFile(usernames.join('\r\n'),`usernames-${usernames.length}-${stamp}.txt`);toast(`${usernames.length} username diexport.`)}catch(e){console.error(e);toast('Export Username gagal: '+String(e.message||e).slice(0,100))}}
  async function copyUsernames(){try{const usernames=usernameList();if(!usernames.length){toast('Tidak ada username.');return}await navigator.clipboard.writeText(usernames.join('\n'));toast(`${usernames.length} username dicopy.`)}catch(e){console.error(e);toast('Copy username gagal.')}}
  function ensureButtons(){ensureDialogs();const quick=document.querySelector('.quick-list');if(!quick)return;if(!document.getElementById('pasteUpcBtn')){const b=document.createElement('button');b.id='pasteUpcBtn';b.innerHTML='⌨ <span>Paste UPC</span>';b.onclick=()=>{if(!isVaultUnlocked()){toast('Unlock vault dulu.');return}document.getElementById('pasteUpcDialog').showModal()};quick.insertBefore(b,document.getElementById('quickSyncBtn')||null)}if(!document.getElementById('exportUpcBtn')){const b=document.createElement('button');b.id='exportUpcBtn';b.innerHTML='⇩ <span>Export UPC</span>';b.onclick=()=>{if(!isVaultUnlocked()){toast('Unlock vault dulu.');return}refreshExportCount();document.getElementById('exportUpcDialog').showModal()};quick.insertBefore(b,document.getElementById('quickSyncBtn')||null)}if(!document.getElementById('exportUsernameBtn')){const b=document.createElement('button');b.id='exportUsernameBtn';b.innerHTML='⇩ <span>Export Username</span>';b.onclick=()=>{if(!isVaultUnlocked()){toast('Unlock vault dulu.');return}refreshUsernameExportCount();document.getElementById('exportUsernameDialog').showModal()};quick.insertBefore(b,document.getElementById('quickSyncBtn')||null)}}
  const baseRender=render;render=function(){baseRender();ensureButtons()};ensureButtons();
})();
